name: Build and Deploy
permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        uses: pnpm/setup@v2
        with:
          cache: true
          install: true

      - name: Core file obfuscate
        run: pnpm run obfuscate

      - name: Build project
        run: pnpm run build

      - name: Prepare deployment artifact
        run: |
          pnpm --filter=urlate deploy ./deploy
          cp ./src/i18n.js ./dist/
          cp -r dist ./deploy/

      - name: Rsync to Production
        run: |
          rsync -azq --delete \
            --exclude='.git/' \
            --exclude='config/config.json' \
            --exclude='logs/' \
            $GITHUB_WORKSPACE/deploy/ URLATE-PRODUCTION:${{secrets.DEPLOY_TARGET}}/

      - name: Restart
        run: |
          ssh URLATE-PRODUCTION \
            "cd '${{secrets.DEPLOY_TARGET}}' && pm2 startOrReload ecosystem.config.js --update-env"
